# %%
import pandas as pd
import numpy as np
from math import pi as pi, log, cos
from sympy import init_printing, symbols, latex, Rational, log as _log, cos as _cos, sqrt, pi as _pi

#init_printing()

# %% symbols

sym = pd.read_csv('../glossary/symbols-english.csv', delimiter='|')
sym.index = sym.key


def prep_key(s):
    return str(s).replace(r'{', '').replace('}', '').replace('\\', '').format(' ', '_')


def add_symbol(df, key, units, description, smb=None):
    if any(df.index.isin([prep_key(key)])):
        print("key: {} is allready in glossary as {}\n not added\n".format(prep_key(key),
                                                                           df[df.key.isin([prep_key(key)])]))
        return
    if smb is None:
        smb = latex(key)
    s = pd.Series({'key': prep_key(key),
                   'symbol': smb,
                   'units': '\\si{{{}}}'.format(units),
                   'description': description})
    sym = df.loc[prep_key(key)] = s


def store_glossary(df: pd.DataFrame):
    df = df.sort_index()
    df.to_csv('../glossary/symbols-english.csv', sep='|', index=False)


Q, D_s, D_p, p_s, p_atm, p_ss, p_v, p_i, p_ro, p_sm, p_rp, v_s, v_p = symbols(
    'Q d_ps d_pp p_s p_atm p_ss p_h p_i p_ro p_sm p_rp v_s v_p')
rho_w, g, S, rho_m, epsilon_s, epsilon_b, a, C = symbols('rho_w g D_s rho_m epsilon_s epsilon_b h_a C_vb')
labda, L, psi, Re, mu, c_t, F_r, F_rxd, theta, rho_s = symbols('lambda L_s psi_m Re mu c_t F_r F_rxd theta_p rho_ds')
H, p_p, p_man = symbols('H p_p p_man')

add_symbol(sym, Q, '\\meter\\cubed\\per\\second', 'volumetric flow')
add_symbol(sym, v_p, '\\meter\\per\\second', 'mixture velocity in discharge line')
add_symbol(sym, v_s, '\\meter\\per\\second', 'mixture velocity in suction line')
add_symbol(sym, D_s, '\\meter', 'volumetric flow')
add_symbol(sym, D_p, '\\meter', 'volumetric flow')
add_symbol(sym, p_s, '\\pascal', 'absolute pressure at the entrance of impeller')
add_symbol(sym, p_p, '\\pascal', 'absolute pressure at the outlet of the dredge pump')
add_symbol(sym, p_man, '\\pascal', 'manometric head of the dredge pump')
add_symbol(sym, p_atm, '\\pascal', 'atmospheric pressure')
add_symbol(sym, p_ss, '\\pascal', 'static pressure generated by surrounding water')
add_symbol(sym, p_v, '\\pascal', 'head, i.e. the velocity required to accelerate the mixture in the pipe')
add_symbol(sym, p_i, '\\pascal', 'pressure loss at the suction inlet')
add_symbol(sym, p_ro, '\\pascal', 'resistance offered by bends, valves, hoses and other obstructions')
add_symbol(sym, p_sm, '\\pascal', 'static head in the suction pipe')
add_symbol(sym, p_rp, '\\pascal', 'resistance of the straight line pipe')
add_symbol(sym, rho_w, '\\kilo\\gram\\per\\cubic\\meter', 'density of water')
add_symbol(sym, rho_m, '\\kilo\\gram\\per\\cubic\\meter', 'density of mixture')
add_symbol(sym, rho_s, '\\kilo\\gram\\per\\cubic\\meter', 'density of soil')
add_symbol(sym, g, '\\meter\\per\\squared\\second', 'standard gravity model')
add_symbol(sym, S, '\\meter', 'suction depth')
add_symbol(sym, epsilon_s, '-', 'resistance coefficient of the suction inlet')
add_symbol(sym, epsilon_b, '-', 'resistance coefficient of the bends, valves, hoses and other obstructions')
add_symbol(sym, a, '\\meter', 'height of water level above center line of a pump')
add_symbol(sym, C, '-', 'transportation concentration')
add_symbol(sym, labda, '-', 'friction factor of a straight pipe')
add_symbol(sym, L, '\\meter', 'length of suction line')
add_symbol(sym, psi, '-', 'Durand_Condolios mixture correction')
add_symbol(sym, Re, '-', 'Reynolds Number')
add_symbol(sym, mu, '\\pascal\\second', 'dynamic viscosity')
add_symbol(sym, c_t, '-', 'volumetric concentration')
add_symbol(sym, F_r, '-', 'Froude number for a pipeline')
add_symbol(sym, F_rxd, '-', 'Froude number of the grains')
add_symbol(sym, theta, '\\degree', 'inclination of the pipeline')
add_symbol(sym, H, '\\meter', 'vertical distance between center of the pump and the elevation of the pipeline')

#store_glossary(sym)

# %% equations

eq = {}


def save_to_tex(eq):
    for k, v in eq.items():
        with open('../equations/{}.tex'.format(k), 'w') as f:
            f.write(v)


# %% conversion


def export_latex(expr, name):
    smbls = list(expr.free_symbols)
    for s in smbls:
        s.name = '<{}>'.format(s)
        
    lstr = latex(expr)
    for s in smbls:
        ss = prep_key(s)
        glss = r'\gls{{sym-{}}}'.format(ss)
        lstr = lstr.replace(latex(s), glss)
    hdr = '% !TeX root = ../../report.tex\n% !TeX spellcheck = en - US\n% !TeX encoding = UTF - 8\n\n'
    return '{}\\begin{{equation}}\\label{{eq:{}}}\n  \\gls{{sym-{}}} = {}\n\\end{{equation}}'.format(hdr,
                                                                                                     prep_key(name),
                                                                                                     prep_key(name),
                                                                                                     lstr).replace('<',
                                                                                                                   '').replace(
        '>', '')


# %% mixture velocity


def _v(Q, D):
    return Q / (np.pi / 4 * D ** 2)


eq['v_s'] = export_latex(_v(Q, D_s), v_s)
eq['v_p'] = export_latex(_v(Q, D_p), v_p)


# %% pressure


def _sum_p(*args):
    return sum(args)


def _p_ss(rho_w, g, S):
    return rho_w * g * S  # / 1000


def _p_v(rho_m, v_s):
    return 1/2 * rho_m * v_s ** 2  # / 1000


def _p_i_ro(eps, rho, v_s):
    return eps * 1/2 * rho * v_s ** 2  # / 1000


def _p_sm(rho_m, g, S, a, C):
    return rho_m * g * (S - a) * C  # / 1000


def _p_rp(labda, L, D_s, rho_w, v_s, psi):
    return labda * L / D_s * 1/2 * rho_w * v_s ** 2 * psi  # / 1000 


def _labda(Re):
    return 0.31 * (np.log(Re) - 1) ** -2


def _Re(v_s, D_s, mu):
    return v_s * D_s / mu


def _psi(c_t, F_r, F_rxd, theta):
    return 1 + 180 * c_t * F_r**-3 * F_rxd**1.5 * np.cos(theta)


def _c_t(rho_m, rho_w, rho_s):
    return (rho_m - rho_w) / (rho_s - rho_w)


def _F_r(v_s, g, D_s):
    return v_s / (g * D_s)**-2


def _p_p(rho_m, v_s, v_p):
    return 1/2 * rho_m * v_s ** 2  # / 1000


def _p_man(p_p, p_s):
    return p_p - p_s


# eq['p_s'] = export_latex(_sum_p(p_atm, p_ss, -p_v, -p_i, -p_ro, -p_sm, -p_rp), p_s)
# 
# eq['p_ss'] = export_latex(_p_ss(rho_w, g, S), p_ss)
# 
# eq['p_v'] = export_latex(_p_v(rho_m, v_s), p_v)
# 
# eq['p_i'] = export_latex(_p_i_ro(epsilon_s, rho_m, v_s), p_i)
# 
# eq['p_ro'] = export_latex(_p_i_ro(epsilon_b, rho_m, v_s), p_ro)
# 
# eq['p_sm'] = export_latex(_p_sm(rho_m, g, S, a, C), p_sm)
# 
# eq['p_rp'] = export_latex(_p_rp(labda, L, D_s, rho_w, v_s, psi), p_rp)
# 
# eq['labda'] = export_latex(_labda(Re), labda)
# 
# eq['Re'] = export_latex(_Re(v_s, D_s, mu), Re)
# 
# eq['psi'] = export_latex(_psi(c_t, F_r, F_rxd, theta), psi)
# 
# eq['c_t'] = export_latex(_c_t(rho_m, rho_w, rho_s), c_t)
# 
# eq['F_r'] = export_latex(_F_r(v_s, g, D_s), F_r)
# 
# eq['p_p'] = export_latex(_p_p(rho_m, v_s, v_p), p_p)
# 
# eq['p_man'] = export_latex(_p_man(p_p, p_s), p_man)

#save_to_tex(eq)

#%% Q_h graph

from pint import UnitRegistry
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

u = UnitRegistry()
u.setup_matplotlib()

p_atm = (1. * u.atmosphere).to('Pa')

L_p = 200. * u.m
L_s = 10. * u.m
L_a = 7. * u.m
theta = 10. * u.deg
S = 30. * u.m
H = 32. * u.m
a = S - L_a * np.sin(theta.to('rad').m)

D_s = 100. * u.mm
D_p = 150. * u.mm

epsilon_b = 0.4
epsilon_s = 0.4

rho_w = 999. * u.kg / u.m ** 3
rho_m = 1400. * u.kg / u.m ** 3
rho_s = 2650. * u.kg / u.m ** 3
mu = 1.17e-6 * u.m ** 2 / u.s

C = 1.
F_rxd = 0.501

g = (1. * u.g0).to_base_units()

Q = np.linspace(0.02, 0.14, 100) * u.m ** 3 / u.s
v_s = _v(Q, D_s)
v_p = _v(Q, D_p)

#%% Suction Side
F_r = _F_r(v_s.to('m/s').m, g.to('m/s**2').m, D_s.to('m').m)

c_t = _c_t(rho_m, rho_w, rho_s)

psi = _psi(c_t, F_r, F_rxd, theta.to('rad'))

Re = _Re(v_s, D_s, mu)

labda = _labda(Re)

p_rp = _p_rp(labda, L_s, D_s, rho_w, v_s, psi)

p_sm = _p_sm(rho_m, g, S, a, C)

p_ro = _p_i_ro(epsilon_b, rho_m, v_s)

p_i = _p_i_ro(epsilon_s, rho_m, v_s)

p_v = _p_v(rho_m, v_s)

p_ss = _p_ss(rho_w, g, S)

p_s = p_atm + p_ss - p_v - p_i - p_ro - p_sm - p_rp

#%% pressure side

p_v = 1/2 * rho_m * (v_p - v_s)**2

p_sm = rho_m * g * (H + a)

p_ro = epsilon_b * rho_m * v_p**2

F_r = v_p.to('m/s').m / (g.to('m/s**2').m * D_p.to('m').m)**-2

psi = 1 + 180 * c_t * F_r * F_rxd * np.cos(theta)

Re = v_p * D_p / mu

labda = _labda(Re)

p_rp = labda * L_p / D_p * 1/2 * rho_w * v_p**2 * psi

p_p = p_v + p_rp + p_ro + p_sm + p_atm

p_man = p_p - p_s

#%%

# df_l = pd.DataFrame(dict(zip(['Q [m^3/s]', 'p [Pa]', 'system'], [Q.to('m**3/s').m, p_s.to('Pa').m, ['pipe'] * len(p_s)])))
# df_p = pd.DataFrame({'Q [m^3/s]': [0.03, 0.085, 0.165],
#                      'p [Pa]': [518e3, 475e3, 270e3],
#                      'system': ['TT15-55 pump'] * 3})
# 
# df = pd.concat([df_p, df_l])
# sns.set()
# sns.set(style="whitegrid")
# sns.set_context("paper")
# pal = sns.color_palette("Reds", n_colors=2)
# sns.lineplot(x='Q [m^3/s]', y='p [Pa]', data=df_l, hue='system')

